name: SlapperCooldown
author: jojoe77777
version: 1.0.0
main: jojoe77777\SlapperCooldown\SlapperCooldown
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
website: https://github.com/jojoe77777/SlapperCooldown
depend: [Slapper]